export const MUSIC_LIST = [
  {
    title: "Chuva de Arroz",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description:
      "Uma linda canção romântica, perfeita para embalar corações apaixonados.",
    link: "https://open.spotify.com/intl-pt/track/1FCvRATk4Wa30LW608ecEN?si=1be8b7292ca044d1",
  },
  {
    title: "Vagabundo Apaixonado",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Sertanejo sofrido sobre um amor não correspondido.",
    link: "https://open.spotify.com/intl-pt/track/3xFLoqr4D9zq4ZOGRAt36o?si=37d73e7c87e044ca",
  },
  {
    title: "Sinônimo",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Uma das músicas mais românticas do sertanejo brasileiro.",
    link: "https://open.spotify.com/intl-pt/track/1LDRFQlo5siAzERHfEbpRS?si=382a5eebb87f4a49",
  },
  {
    title: "Que Se Chama Amor",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description:
      "Uma declaração poética sobre o verdadeiro significado do amor.",
    link: "https://open.spotify.com/intl-pt/track/3yfilLeeHLhFjnmIzZhBRc?si=4897b720116f48b2",
  },
  {
    title: "Água de Oceano",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description:
      "Uma balada que fala sobre intensidade e profundidade nos relacionamentos.",
    link: "https://open.spotify.com/intl-pt/track/6XbjPrR0inBrzGBdS1BpXU?si=0abaa50df7ba4374",
  },
  {
    title: "De Quem é a Culpa",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Reflexão sobre términos, mágoas e amores não resolvidos.",
    link: "https://open.spotify.com/intl-pt/track/7ollwW6YUxut3nLqUzAWP1?si=8f992b106613400e",
  },
  {
    title: "Tem que Ser Você",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Aquela música que reafirma que o amor certo é inconfundível.",
    link: "https://open.spotify.com/intl-pt/track/6C347p0KFYpVnsduhe4r6g?si=73c9a5be9e464bb1",
  },
  {
    title: "Como Eu Quero",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Romântica e intensa, fala sobre desejos e cumplicidade.",
    link: "https://open.spotify.com/intl-pt/track/7MVCzhn2c1gspz2I03uzTp?si=83ef70165d9342ad",
  },
  {
    title: "Brilho de Facas",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Canção forte sobre desilusões amorosas.",
    link: "https://open.spotify.com/intl-pt/track/68kJrcVSJm5HMxB6pnNm9h?si=c12aa43f60ab453a",
  },
  {
    title: "Ontem à Noite",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Uma história que se desenrola em uma noite cheia de emoções.",
    link: "https://open.spotify.com/intl-pt/track/3KnIvDUq5ciKmHlLgNQR3o?si=d7d70748f3474d62",
  },
  {
    title: "João de Barro",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Música poética sobre construir, amar e proteger quem se ama.",
    link: "https://open.spotify.com/intl-pt/track/5lJpm6RWHHdwoGATBUNP6D?si=44ceafbc3d694fbf",
  },
  {
    title: "Jogado na Prisão",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "Expressa a dor de estar preso em sentimentos e lembranças.",
    link: "https://open.spotify.com/intl-pt/track/3STEhmd7I1b6RKuKo3Rtj6?si=22f14908746c4925",
  },
  {
    title: "Juliana Bar da Boa",
    artist: "Natanzinho Lima",
    album: "De Bar em Bar 6",
    cover: "/de-bar-em-bar-6.jpg",
    description: "História descontraída e divertida contada no bar da Juliana.",
    link: "https://open.spotify.com/intl-pt/track/0stqCmN05bktvSu2j3CX7q?si=6527a2e5473544d9",
  },
];
